<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="7" name="pytest" skipped="3" tests="16" time="0.194"><testcase classname="test_addition" file="test_addition.py" line="6" name="test_add_1" time="0.001"><skipped message="unconditional skip" type="pytest.skip">test_addition.py:6: unconditional skip</skipped></testcase><testcase classname="test_addition" file="test_addition.py" line="10" name="test_add_2" time="0.001"><skipped message="unconditional skip" type="pytest.skip">test_addition.py:10: unconditional skip</skipped></testcase><testcase classname="test_addition" file="test_addition.py" line="14" name="test_add_3" time="0.004"></testcase><testcase classname="test_addition" file="test_addition.py" line="18" name="test_add_4" time="0.004"><skipped message="expected test failure"></skipped></testcase><testcase classname="test_addition" file="test_addition.py" line="22" name="test_add_5" time="0.004"></testcase><testcase classname="test_addition" file="test_addition.py" line="25" name="test_add_6" time="0.003"><failure message="AssertionError: failed
assert 5 == 6
  -5
  +6">def test_add_6():
&gt;   	assert 3+2 == 6,&quot;failed&quot;
E    AssertionError: failed
E    assert 5 == 6
E      -5
E      +6

test_addition.py:27: AssertionError</failure></testcase><testcase classname="test_basic_fixture" file="test_basic_fixture.py" line="1" name="test_comparewithAA" time="0.003"><failure message="AssertionError: aa and zz comparison failed
assert 25 == 35
  -25
  +35">supply_AA_BB_CC = [25, 35, 45]

    def test_comparewithAA(supply_AA_BB_CC):
    	zz=35
&gt;   	assert supply_AA_BB_CC[0]==zz,&quot;aa and zz comparison failed&quot;
E    AssertionError: aa and zz comparison failed
E    assert 25 == 35
E      -25
E      +35

test_basic_fixture.py:4: AssertionError</failure></testcase><testcase classname="test_basic_fixture" file="test_basic_fixture.py" line="5" name="test_comparewithBB" time="0.002"></testcase><testcase classname="test_basic_fixture" file="test_basic_fixture.py" line="9" name="test_comparewithCC" time="0.002"><failure message="AssertionError: cc and zz comparison failed
assert 45 == 35
  -45
  +35">supply_AA_BB_CC = [25, 35, 45]

    def test_comparewithCC(supply_AA_BB_CC):
    	zz=35
&gt;   	assert supply_AA_BB_CC[2]==zz,&quot;cc and zz comparison failed&quot;
E    AssertionError: cc and zz comparison failed
E    assert 45 == 35
E      -45
E      +35

test_basic_fixture.py:12: AssertionError</failure></testcase><testcase classname="test_basic_fixture2" file="test_basic_fixture2.py" line="1" name="test_comparewithAA_file2" time="0.000"></testcase><testcase classname="test_basic_fixture2" file="test_basic_fixture2.py" line="5" name="test_comparewithBB_file2" time="0.003"><failure message="AssertionError: bb and zz comparison failed
assert 35 == 25
  -35
  +25">supply_AA_BB_CC = [25, 35, 45]

    def test_comparewithBB_file2(supply_AA_BB_CC):
    	zz=25
&gt;   	assert supply_AA_BB_CC[1]==zz,&quot;bb and zz comparison failed&quot;
E    AssertionError: bb and zz comparison failed
E    assert 35 == 25
E      -35
E      +25

test_basic_fixture2.py:8: AssertionError</failure></testcase><testcase classname="test_basic_fixture2" file="test_basic_fixture2.py" line="9" name="test_comparewithCC_file2" time="0.002"><failure message="AssertionError: cc and zz comparison failed
assert 45 == 25
  -45
  +25">supply_AA_BB_CC = [25, 35, 45]

    def test_comparewithCC_file2(supply_AA_BB_CC):
    	zz=25
&gt;   	assert supply_AA_BB_CC[2]==zz,&quot;cc and zz comparison failed&quot;
E    AssertionError: cc and zz comparison failed
E    assert 45 == 25
E      -45
E      +25

test_basic_fixture2.py:12: AssertionError</failure></testcase><testcase classname="test_sample" file="test_sample.py" line="1" name="test_file1_method1" time="0.004"><failure message="AssertionError: test failed because x=5 y=6
assert 5 == 6
  -5
  +6">@pytest.mark.set1
    def test_file1_method1():
    	x=5
    	y=6
    	assert x+1 == y,&quot;test failed&quot;
&gt;   	assert x == y,&quot;test failed because x=&quot; + str(x) + &quot; y=&quot; + str(y)
E    AssertionError: test failed because x=5 y=6
E    assert 5 == 6
E      -5
E      +6

test_sample.py:7: AssertionError</failure></testcase><testcase classname="test_sample" file="test_sample.py" line="8" name="test_file1_method2" time="0.001"></testcase><testcase classname="test_sample2" file="test_sample2.py" line="1" name="test_file2_method1" time="0.001"><failure message="AssertionError: test failed because x=5 y=6
assert 5 == 6
  -5
  +6">@pytest.mark.set1
    def test_file2_method1():
    	x=5
    	y=6
    	assert x+1 == y,&quot;test failed&quot;
&gt;   	assert x == y,&quot;test failed because x=&quot; + str(x) + &quot; y=&quot; + str(y)
E    AssertionError: test failed because x=5 y=6
E    assert 5 == 6
E      -5
E      +6

test_sample2.py:7: AssertionError</failure></testcase><testcase classname="test_sample2" file="test_sample2.py" line="8" name="test_file2_method2" time="0.000"></testcase></testsuite>